export const STATE_CAR_MODEL_LIST = 'STATE_CAR_MODEL_LIST';
export const STATE_CAR_MODEL_ITEM = 'STATE_CAR_MODEL_ITEM';
export const STATE_AUTHORIZATION = 'STATE_AUTHORIZATION';
export const STATE_NAVIGATION = 'STATE_NAVIGATION';

