export const STORE_CAR_MODEL_LIST = 'STORE_CAR_MODEL_LIST';
export const STORE_CAR_MODEL_ITEM = 'STORE_CAR_MODEL_ITEM';
export const STORE_AUTHORIZATION = 'STORE_AUTHORIZATION';
export const STORE_NAVIGATION = 'STORE_NAVIGATION';

